name: Build and Push Vultr DDNS Docker Image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'apps/vultr-ddns/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/run-pnpm-test.yml
    with:
      working-directory: ./apps/vultr-ddns
      vultr-api-key: ${{ secrets.VULTR_API_KEY }}
  build:
    uses: ./.github/workflows/docker-build.yml
    needs: test
    secrets: inherit
    with:
      docker-file-path: ./Dockerfile
      docker-build-target: vultr-ddns
